log:
  level: test
  file: ./log.log
  output: [stdout, file]
metabase_domain: https://your-metabase-instance.com
database:
  port: 5432
  host: localhost
  user: your_user
  password: your_password
  name: notification_bot
timeout:
  database_connect: 10s
  bot_poll: 10s
  shutdown: 5s
bot:
  telegram_token: your_telegram_token
  CleanUpTime: 5m
smb:
  adress: your fs address
  user: user
  password: password
  domain: domain
smtp:
  host: imap.example.com
  port: 235
  email: jhon_doe@example.com
  password: jhon_doe_password

